name: learning_translate
description: The easy way to use ML Kit for text translation in Flutter.
version: 0.0.4
# author: Salman S
homepage: https://github.com/salkuadrat/learning/tree/master/packages/learning_translate
repository: https://github.com/salkuadrat/learning/tree/master/packages/learning_translate

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.salkuadrat.learning.learning_translate
        pluginClass: LearningTranslatePlugin
      ios:
        pluginClass: LearningTranslatePlugin
